---
abstract: 'A Perl message queue based on POE that uses STOMP as its communication protocol.'
author:
  - 'David Snopek'
build_requires:
  Data::Dumper: 0
  ExtUtils::MakeMaker: 6.36
  File::Temp: 0
  Test::Exception: 0
  Test::MockObject: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Component-MessageQueue
no_index:
  directory:
    - examples
    - inc
    - t
recommends:
  YAML::Syck: 0
requires:
  Best: 0
  Carp: 0
  DBD::SQLite: 1.13
  DBI: 0
  Data::UUID: 0
  Event::Notify: 0
  Exception::Class::DBI: 0
  Exception::Class::TryCatch: 0
  Heap: 0.8
  Heap::Fibonacci: 0.8
  IO::File: 0
  IO::String: 0
  Moose: 2.0201
  MooseX::AttributeHelpers: 0.08
  MooseX::MultiInitArg: 0
  Net::Stomp: 0
  POE: 0.38
  POE::Component::Generic: 0.1001
  POE::Component::Logger: 0
  POE::Component::Server::TCP: 0
  POE::Filter::Stomp: 0.04
  POE::Wheel::ReadWrite: 0
  YAML: 0
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: 0.2.13
