abstract: A Perl message queue based on POE that uses STOMP as its communication protocol.
author: David Snopek
build_requires:
  Data::Dumper: 0
  File::Temp: 0
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.64
license: gpl
name: POE-Component-MessageQueue
no_index:
  directory:
    - test
    - examples
    - inc
    - t
recommends:
  YAML::Syck: 0
requires:
  Best: 0
  Carp: 0
  DBD::SQLite: 1.13
  DBI: 0
  Event::Notify: 0
  Exception::Class::DBI: 0
  Exception::Class::TryCatch: 0
  IO::File: 0
  IO::String: 0
  Net::Stomp: 0
  POE: 0.38
  POE::Component::Generic: 0.1001
  POE::Component::Logger: 0
  POE::Component::Server::TCP: 0
  POE::Wheel::ReadWrite: 0
  YAML: 0
version: 0.1.7
